config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get '/main_page' => "homes#main_page", as: "main_page"
  get '/users/my_page' => "users#show", as: "user_my_page"
  resources :users, only: [:edit, :update]
  resources :categories, only: [:index, :create, :edit, :destroy, :update]
  resources :months, only: [:new, :create, :index, :show, :edit, :update, :destroy], shallow: true do
    resources :details, only: [:new, :create, :index, :edit, :update, :destroy, :search] do
      collection do
        get :search
      end
    end
    resources :budgets, only: [:new, :create, :destroy, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :user
  has_many :details, dependent: :destroy
  has_one :budget, dependent: :destroy

  validates :user_id, presence: true
  validates :month, presence: true
  validates :balance, presence: true
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def new
    @month = Month.new
    @latest_month = Month.where(user_id: current_user.id).includes(:user).order(month: :desc).first
    total_for_each
  end

  def create
    @month = Month.new(month_params)

    @data = Month.find_by(user_id: current_user.id, month: @month.month)
    @month.balance_last = @month.balance #月初残高と月末残高を同一と定義

    if !@data.present?
      @month.user_id = current_user.id
      if @month.save
        redirect_to months_path
      else
        render :new, danger
      end
    else
      redirect_to months_path
    end
  end

  def index
    @months = Month.where(user_id: current_user.id).order(month: :desc).page(params[:page]).per(5)
    @month = Month.find_by(user_id: current_user.id, month: Date.today.beginning_of_month)
    if @month.present?
      @month_chart = Month.where(user_id: current_user.id).includes(:user).order(month: :asc).last(12).pluck(:month, :balance_last)
      @month_chart_max = Month.where(user_id: current_user.id).includes(:user).order(month: :asc).last(12).pluck(:balance_last).max
    else
      redirect_to main_page_path
    end
  end

  def edit
    @month = Month.find_by(user_id: current_user.id, id: params[:id])
  end

  def update
    @month = Month.find_by(user_id: current_user.id, id: params[:id])
    total_for_each
    @month.update(month_params)
    @month.balance_last = @month.balance + @balance_of_payments
    if @month.save
      redirect_to months_path, notice: "月初残高を更新しました。"
    else
      render :edit, danger: "更新できませんでした。"
    end
  end

  def destroy
    @month = Month.find(params[:id])
    @month.destroy
    flash[:alert] = "#{@month.month.strftime("%Y年 %m月")}の家計簿は削除しました。"
    redirect_to months_path
  end

  private
  def month_params
    params.require(:month).permit(:user_id, :month, :balance)
  end

  def total_for_each
    @income_total = Detail.where(user_id: current_user.id, month_id: params[:id]).includes(:user).sum(:income)
    @spending_total = Detail.where(user_id: current_user.id, month_id: params[:id]).includes(:user).sum(:spending)
    @balance_of_payments = @income_total - @spending_total
  end
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/months/edit.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>家計簿の編集</h3><br>
      <div>
        <%= form_with model: @month, url: month_path, method: :patch, local: true do |f| %>
          <div>
            <%= f.label :month, "家計簿", class: "control-label" %>
            <%= f.date_select :month, {use_month_numbers: true, start_year: 2021, date_separator: '年', discard_day: true}, {class: "form-control"} %>月
          </div>
          <div>
            <%= f.label :balance_last, "月末口座残高", class: "control-label" %><br>
            <%= f.text_field :balance_last, class:"category_name" %>
            <%= f.submit '残高を更新する', class:"btn btn-primary" %>
          </div>
          <div>
            <%= link_to "キャンセル", months_path, class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/months/index.html.erb
<div class="container">
  <div class="row">
    <div><br>
      <h3>家計簿一覧</h3><br>
    <!-- ここにグラフを挿入  -->
      <% if @month_chart_max > 10000 %>
        <%= area_chart @month_chart.map { |month, balance_last| [month.strftime('%-m月'), balance_last / 10000] }, suffix: "万円" %>
      <% else %>
        <%= area_chart @month_chart.map { |month, balance_last| [month.strftime('%-m月'), balance_last] }, suffix: "円" %>
      <% end %>
    <!-- ここまで -->
      <div>
        <p>家計簿一覧</p>
        <div>
          <%= link_to "家計簿作成", new_month_path, class: "btn btn-primary btn-sm" %>
        </div>
        <table class="table">
          <% @months.each do |month| %>
            <thead>
              <tr>
                <th>
                  <%= link_to "#{month.month.strftime("%Y年 %-m月")}", month_details_path(month.id), style:"color: black;" %>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>月末残高</td>
                <td><%= month.balance_last.floor.to_s(:delimited, delimiter: ',') %>円</td>
                <td><%= link_to "編集", edit_month_path(month.id), class: "btn btn-secondary" %></td>
                <td><%= link_to "削除", month_path(month.id), method: :delete, class: "btn btn-danger" %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
        <%= paginate @months %>
      </div>
    </div>
  </div>
  <div><!-- +ボタンを作成  -->
    <% if user_signed_in? %>
      <%= render 'details/footer' %>
    <% end %>
  </div>
</div>

app/views/months/new.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>家計簿の追加</h3><br>
      <div>
        <%= form_with model: @month, url: months_path, local: true do |f| %>
          <table class="table">
            <tr>
              <th><%= f.label :month, "家計簿", class: "control-label" %></th>
              <td><%= f.date_select :month, {use_month_numbers: true, start_year: 2021, date_separator: '年', discard_day: true}, {class: "form-control"} %>月</td>
            </tr>
            <tr>
              <th>前月口座残高</th>
              <td></td>
            </tr>
            <tr>
              <th><%= f.label :balance, "口座残高", class: "control-label" %><br></th>
              <td><%= f.text_field :balance, class:"form-control" %></td>
            </tr>
          </table>
          <%= f.submit '登録', class:"btn btn-primary" %>
          <div>
            <%= link_to "キャンセル", months_path, class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/months/show.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3><%= @month.month.strftime("%Y年 %m月") %></h3><br>
    <!-- 検索機能実装  -->
      <div>
        <%= link_to "入出金登録", new_month_detail_path(@month), class: "btn btn-secondary btn-sm" %>

      </div>





    <div>
      <%= link_to "一覧に戻る", months_path, class: "btn btn-secondary btn-sm" %>
    </div>


    </div>
  </div>
</div>