config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get '/main_page' => "homes#main_page", as: "main_page"
  get '/users/my_page' => "users#show", as: "user_my_page"
  resources :users, only: [:edit, :update]
  resources :categories, only: [:index, :create, :edit, :destroy, :update]
  resources :months, only: [:new, :create, :index, :show, :edit, :update, :destroy], shallow: true do
    resources :details, only: [:new, :create, :index, :edit, :update, :destroy, :search] do
      collection do
        get :search
      end
    end
    resources :budgets, only: [:new, :create, :destroy, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :month

  validates :user_id, presence: true
  validates :month_id, presence: true
  validates :amount, presence: true
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  def new
    @budget = Budget.new
  end

  def create
    @budgets = Budget.all # 追加
    @add = Budget.new(budget_params)
    if !authenticate_budget
      @add.month_id = params[:month_id]
      @add.user_id = current_user.id
      if @add.save
        render :index, success: '予算を設定しました'
      else
        render :index, danger: '予算を設定できませんでした'
      end
    else
      render :index, danger: '予算は既に設定されています'
    end
  end

  def index
    @month = Month.find_by(user_id: current_user.id, id: params[:month_id])
    authenticate_budget
    @budgets = Budget.where(user_id: current_user.id).order(month_id: :asc, id: :asc)
  end

  def destroy
    @budgets = Budget.all # 追加
    @budget = Budget.find(params[:id])
    @budget.destroy
  end

  private

  def budget_params
    params.permit(:amount)
  end

  def authenticate_budget
    @budget = Budget.find_by(user_id: current_user.id, month_id: params[:month_id])
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_index.html.erb
<% @budgets.each do |budget| %>
  <thead>
    <tr>
      <th>
        <%= budget.month.month.strftime("%Y年%-m月") %>の予算
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= budget.amount.to_s(:delimited, delimiter: ',') %></td>
      <td><%= link_to "削除", budget_path(budget.id), method: :delete, remote: true, class: "btn btn-danger btn-sm" %></td>
    </tr>
  </tbody>
<% end %>

app/views/budgets/create.js.erb
$('#budget').html("<%= j(render 'budgets/index', budgets: @budgets) %>");
$("text_area").val("");
$("#text").val("");

app/views/budgets/destroy.js.erb
$('#budget').html("<%= j(render 'budgets/index', budgets: @budgets) %>");

app/views/budgets/index.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>予算</h3>
      <% flash[:notice] %>
      <div>
        <%= form_with model: @add, url: month_budgets_path, method: :post do |f| %>
          <div>
            <%= f.label :amount, "予算登録" %>
            <%= f.text_field :amount, placeholder: "金額を入力してください", class: "form-control" %>
            <%= f.submit '登録', class:"btn btn-primary btn-sm" %>
          </div>
        <% end %>
      </div><br>
    <div>
        <table id="budget" class="table">
          <!--ここから非同期-->
            <%= render 'budgets/index', budgets: @budgets %>
          <!--ここまで-->
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <%= link_to "キャンセル", user_my_page_path, class: "btn btn-secondary btn-sm" %>
  </div>
</div>

app/views/budgets/new.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>予算設定</h3><br>
      <div>
        <%= form_with model: @budget, url: budgets_path, local: true do |f| %>
          <div>
            <%= f.label :month_id, "何月の予算ですか？", class: "control-label" %><br>
            <!-- 余力があれば修正  -->
            <%= f.collection_select :month_id, Month.all, :id, :month, include_blank: " --選択してください-- " %>
          </div>
          <div>
            <%= f.label :amount, "予算", class: "control-label" %>
            <%= f.text_field :amount, placeholder: "金額を入力", class: "form-control" %>
          </div>
          <div>
            <%= f.submit '登録', class:"btn btn-primary btn-sm" %>
          </div>
          <div>
            <%= link_to "キャンセル", months_path, class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/budgets/show.html.erb
<h1>Budgets#show</h1>
<p>Find me in app/views/budgets/show.html.erb</p>