config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get '/main_page' => "homes#main_page", as: "main_page"
  get '/users/my_page' => "users#show", as: "user_my_page"
  resources :users, only: [:edit, :update]
  resources :categories, only: [:index, :create, :edit, :destroy, :update]
  resources :months, only: [:new, :create, :index, :show, :edit, :update, :destroy], shallow: true do
    resources :details, only: [:new, :create, :index, :edit, :update, :destroy, :search] do
      collection do
        get :search
      end
    end
    resources :budgets, only: [:new, :create, :destroy, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :user
  belongs_to :month
  belongs_to :category

  validates :user_id, presence: true
  validates :month_id, presence: true
  validates :category_id, presence: true
  validates :player, presence: true
  validates :status, presence: true
  validates :date, presence: true
  validates :note, length: { maximum: 15 }

  # enum 設定
  enum player: { by_him: 0, by_her: 1 }

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :total_for_each
  # before_action :search
  require 'csv'

  def new
    @detail = Detail.new
  end

  def create
    detail = Detail.new(detail_params)
    detail.user_id = current_user.id
    detail.month_id = params[:month_id]
    detail.save
    redirect_to month_details_path
    #else
    #render "new"
    #end
  end

  # def search
    # ransackの検索メソッド
    # @q = Detail.ransack(params[:q])
    # detailsの検索結果一覧
    # @search_details = @q.result(distinct: true).includes(:month).order(date: :asc, id: :asc).page(params[:page]).per(5)
  # end

  def index
    @this_month = Month.find_by(user_id: current_user.id, month: Date.today.beginning_of_month)
    @month = Month.find_by(user_id: current_user.id, id: params[:month_id])
    @details = Detail.where(user_id: current_user.id, month_id: params[:month_id]).includes(:month).order(date: :desc, id: :desc).page(params[:page]).per(10)
    #@details = current_user.details_in_month(params[:month_id]).order(date: :desc, id: :desc).page(params[:page]).per(10)


    respond_to do |format|
      format.html
      format.csv do |csv|
        send_posts_csv(@details)
      end
    end
  end

  def edit
    @detail = Detail.find(params[:id])
  end

  def update
    @detail = Detail.find_by(user_id: current_user.id, id: params[:id])
    @detail.update(detail_params)
    redirect_to month_details_path(@detail.month_id)
  end

  def destroy
    @detail = Detail.find_by(user_id: current_user.id, id: params[:id])
    @detail.destroy
    flash[:alert] = "明細を削除しました。"
    redirect_to month_details_path(@detail.month_id)
  end

  private
  def detail_params
    params.require(:detail).permit(:income, :spending, :note, :player, :date, :category_id)
  end

  def detail_params_edit
    params.require(:detail).permit(:income, :spending, :note, :player, :date, :category_id)
  end

  def total_for_each
    # details = Detail.where(user_id: current_user.id).includes(:month)
    # details_in_month = details.where(month_id: params[:id])
    # @income_total = details_in_month.sum(:income)
    # @spending_total = details_in_month.sum(:spending)

    #details_before_today = details_in_month.where(status: :true).where("date <= ?", Date.today)
    #@income_total_true_before_today = details_before_today.sum(:income)
    #@spending_total_true_before_today = details_before_today.sum(:spending)

    @income_total = Detail.where(user_id: current_user.id, month_id: params[:id]).includes(:month).sum(:income)
    @spending_total = Detail.where(user_id: current_user.id, month_id: params[:id]).includes(:month).sum(:spending)
    @income_total_true_before_today = Detail.where(user_id: current_user.id, month_id: params[:month_id], status: :true).where("date <= ?", Date.today).includes(:month).sum(:income)
    @spending_total_true_before_today = Detail.where(user_id: current_user.id, month_id: params[:month_id], status: :true).where("date <= ?", Date.today).includes(:month).sum(:spending)
    @balance_of_payments = @income_total - @spending_total
  end

  def send_posts_csv(details)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      column_names = %w(日付 カテゴリ名 収入 支出 支払元)
      csv << column_names
      details.each do |detail|
        column_values = [
          detail.date.strftime("%-m月%-d日"), # date
          detail.category.name, # category_id
          detail.income, # income
          detail.spending, # spending
          detail.player_i18n, # palyer
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "投稿一覧.csv")
  end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_footer.html.erb
<% if @month.present? %>
  <footer>
    <div class="fixed-btn">
      <%= link_to new_month_detail_path(@month.id) do %>
        <i class="fas fa-plus-circle fa-3x"></i></div>
      <% end %>
    </div>
  </footer>
<% end %>

app/views/details/_header.html.erb
<%= search_form_for @q, url: main_page_path, class:"search-form" do |f| %>
  <%= f.date_field :date_gteq %>
  <%= f.date_field :date_lteq %>
  <%= f.submit "検索", class:"search-button" %>
<% end %>
<% if @search_details.present? %>
  <!--検索がヒットした場合-->
  <table class="table">
    <% @search_details.each do |detail| %>
      <tbody>
        <tr>
          <td><%= detail.date.strftime("%-m月%-d日") %></td>
          <td>
            <%= attachment_image_tag detail.category, :image, size: "30x30", format: 'jpeg', fallback: "no_image.jpeg" %>
          </td>
          <td>
            <%= detail.category.name %>
          </td>
          </td>
            <% if detail.income.present? %>
              <td>+<%= detail.income.floor.to_s(:delimited, delimiter: ',') %>円</td>
            <% else %>
              <td>-<%= detail.spending.floor.to_s(:delimited, delimiter: ',') %>円</td>
            <% end %>
          <td><%= detail.note %></td>
          <td><%= detail.player_i18n %></td>
          <td><%= link_to "編集", edit_detail_path(detail.id), class: "btn btn-secondary btn-sm" %></td>
          <td><%= link_to "削除", detail_path(detail.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% else %>
  <!--検索がヒットしなかった場合-->
  <p>検索結果はありません</p>
<% end %>

app/views/details/edit.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>明細編集</h3><br>
      <div>
        <%= form_with model: @detail, method: :patch, local: true do |f| %>
          <!--  支出 or 収入 選択  -->
          <div>
            <%= f.label :spending, "支出", class: "control-label" %>
            <%= f.text_field :spending, class: "form-control", placeholder: "0円" %>
          </div>
          <div>
            <%= f.label :income, "収入", class: "control-label" %>
            <%= f.text_field :income, class: "form-control", placeholder: "0円" %>
          </div>
          <!-- カテゴリ  -->
          <div>
            <%= f.label :category, "カテゴリ", class: "control-label" %>
            <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: " --選択してください-- " %>
          </div>
          <!-- 日付 -->
          <div>
            <%= f.label :date, "日付", class: "control-label" %><br>
            <%= f.date_field :date, class:"form-control", value: Date.today %>
          </div>
          <!-- メモ -->
          <div>
            <%= f.label :note, "詳細", class: "control-label" %>
            <%= f.text_field :note, placeholder: "詳細メモ", class: "form-control" %>
          </div>
          <!-- 支払元 -->
          <div>
            <%= f.label :player, "支払元", class: "control-label" %>
            <%= f.select :player, Detail.players.keys.map{|k| [I18n.t("enums.detail.player.#{k}"), k]}, class: "form-control" %>
          </div>
          <div>
            <%= f.submit '保存', class:"btn btn-primary" %>
          </div>
          <div>
            <%= link_to "キャンセル", month_details_path(@detail.month_id), class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/details/index.html.erb
<div class="container">
  <div class="row">
    <div><br>
      <h3>入出金明細</h3><br>
      <div>
        <%= link_to "CSVを出力", month_details_path(@month.id, format: :csv), class: "btn btn-primary btn-sm" %>
        <%= link_to "家計簿一覧に戻る", months_path, class: "btn btn-secondary btn-sm" %>
      </div><br>
    <!--ここに収支情報-->
      <h5>今月の収支</h5>
      <div>
        <table class="table">
          <tbody>
            <tr>
              <td>収入</td>
              <td><%= "+#{@income_total_true_before_today.to_s(:delimited)}円" %></td>
            </tr>
            <tr>
              <td>支出</td>
              <td><%= "-#{@spending_total_true_before_today.to_s(:delimited)}円" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <table class="table">
          <% @details.each do |detail| %>
            <tbody>
              <tr>
                <td><%= detail.date.strftime("%-m月%-d日") %></td>
                <td>
                  <%= attachment_image_tag detail.category, :image, size: "30x30", format: 'jpeg', fallback: "no_image.jpeg" %>
                </td>
                <td>
                  <%= detail.category.name %>
                </td>
                </td>
                  <% if detail.income.present? %>
                    <td>+<%= detail.income.to_s(:delimited, delimiter: ',') %>円</td>
                  <% else %>
                    <td>-<%= detail.spending.to_s(:delimited, delimiter: ',') %>円</td>
                  <% end %>
                <td><%= detail.note %></td>
                <td><%= detail.player_i18n %></td>
                <td><%= link_to "編集", edit_detail_path(detail.id), class: "btn btn-secondary btn-sm" %></td>
                <td><%= link_to "削除", detail_path(detail.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
        <%= paginate @details %>
        <!-- +ボタンを作成  -->
        <% if user_signed_in? %>
          <%= render 'details/footer' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/details/new.html.erb
<div class="container">
  <div class="row">
    <div><br>
    <h3>明細入力</h3><br>
      <div>
        <%= form_with model: @detail, url: month_details_path, local: true do |f| %>
          <!--  支出 or 収入 選択  -->
          <div>
            <%= f.label :spending, "支出", class: "control-label" %>
            <%= f.text_field :spending, class: "form-control", placeholder: "0円" %>
          </div>
          <div>
            <%= f.label :income, "収入", class: "control-label" %>
            <%= f.text_field :income, class: "form-control", placeholder: "0円" %>
          </div>
          <!-- カテゴリ  -->
          <div>
            <%= f.label :category, "カテゴリ", class: "control-label" %>
            <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: " --選択してください-- " %>
          </div>
          <!-- 日付 -->
          <div>
            <%= f.label :date, "日付", class: "control-label" %><br>
            <%= f.date_field :date, class:"form-control", value: Date.today %>
          </div>
          <!-- メモ -->
          <div>
            <%= f.label :note, "詳細", class: "control-label" %>
            <%= f.text_field :note, placeholder: "詳細メモ", class: "form-control" %>
          </div>
          <!-- 支払元 -->
          <div>
            <%= f.label :player, "支払元", class: "control-label" %>
            <%= f.select :player, Detail.players.keys.map{|k| [I18n.t("enums.detail.player.#{k}"), k]}, class: "form-control" %>
          </div>
          <div>
            <%= f.submit '保存', class:"btn btn-primary" %>
          </div>
          <div>
            <%= link_to "キャンセル", month_details_path, class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/details/show.html.erb
<h1>Details#show</h1>
<p>Find me in app/views/details/show.html.erb</p>