config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get '/main_page' => "homes#main_page", as: "main_page"
  get '/users/my_page' => "users#show", as: "user_my_page"
  resources :users, only: [:edit, :update]
  resources :categories, only: [:index, :create, :edit, :destroy, :update]
  resources :months, only: [:new, :create, :index, :show, :edit, :update, :destroy], shallow: true do
    resources :details, only: [:new, :create, :index, :edit, :update, :destroy, :search] do
      collection do
        get :search
      end
    end
    resources :budgets, only: [:new, :create, :destroy, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cokakekan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-dark", style="background-color: #99CC33">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag 'wallet.png', size: "40x40" %><strong> cokakekan</strong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item", style="margin-right: 10px;">
                  <%= link_to "メインページ", main_page_path %>
                </li>
                <% if @authenticated_this_month.present? %>
                  <li class="nav-item", style="margin-right: 10px;">
                    <%= link_to "家計簿", months_path %>
                  </li>
                  <li class="nav-item", style="margin-right: 10px;">
                    <%= link_to "当月明細", month_details_path(@authenticated_this_month) %>
                  </li>
                  <li class="nav-item", style="margin-right: 10px;">
                    <%= link_to "予算", month_budgets_path(@authenticated_this_month) %>
                  </li>
                <% else %>

                <% end %>
                <li class="nav-item", style="margin-right: 10px;">
                  <%= link_to "マイページ", user_my_page_path(current_user.id) %>
                </li>
                <li class="nav-item", style="margin-right: 10px;">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <%= render 'shared/before_login_header' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>